### ISSUE TITLE
crystal 0.16 support

### ISSUE THREAD

**Issue by dclausen** [andrewsuzuki/termbox-crystal#3]
after upgrading to crystal 0.16 and termbox-crystal d64743ddbe0fe3930523b636726f3fb529978c85 I'm getting:

instantiating 'Termbox::Window:Class#new()'                                                                                          

```
@window = Window.new
                 ^~~
```

instantiating 'Termbox::Window#initialize()'

in ./libs/termbox/termbox/window.cr:14: instantiating 'Termbox::Position:Class#new(Int32, Int32)'

```
  super(Position.new(0, 0), 0, 0)
                 ^~~
```

instantiating 'Termbox::Position#initialize(Int32, Int32)'

in ./libs/termbox/termbox/position.cr:6: Can't infer the type of instance variable '@x' of Termbox::Position

The type of a instance variable, if not declared explicitly with
`@x : Type`, is inferred from assignments to it across
the whole program.

The assignments must look like this:
1. `@x = 1` (or other literals), inferred to the literal's type
2. `@x = Type.new`, type is inferred to be Type
3. `@x = Type.method`, where `method` has a return type
    annotation, type is inferred from it
4. `@x = arg`, with 'arg' being a method argument with a
    type restriction 'Type', type is inferred to be Type
5. `@x = arg`, with 'arg' being a method argument with a
    default value, type is inferred using rules 1, 2 and 3 from it
6. `@x = uninitialized Type`, type is inferred to be Type
7. `@x = LibSome.func`, and `LibSome` is a `lib`, type
    is inferred from that fun.
8. `LibSome.func(out @x)`, and `LibSome` is a `lib`, type
    is inferred from that fun argument.

Other assignments have no effect on its type.

Can't infer the type of instance variable '@x' of Termbox::Position

```
def initialize(@x : Int, @y : Int)
               ^~
```

**Comment by notramo** [comment]
Is this still an issue?

**Comment by Lukc** [comment]
I just built the examples on Crystal 0.25.1. This is no longer an issue.
