### ISSUE TITLE
Error when compiling on Manjaro Linux

### ISSUE THREAD

**Issue by webmastak** [andrewsuzuki/termbox-crystal#8]
crystal: 0.29.0
```
 crystal build src/colorls.cr --no-debug --release
/usr/bin/ld: cannot find -ltermbox (this usually means you need to install the development package for libtermbox)
collect2: error: ld execution completed with return code 1
Error: execution of command failed with code: 1: `cc "${@}" -o '/home/andrew/crystal/colorls-cr/colorls' -lffi -rdynamic  -lyaml -L/usr/local/lib -ltermbox -lpcre -lm -lgc -lpthread /usr/lib/crystal/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`
```

**Comment by Lukc** [comment]
This is not directly related to termbox-crystal. The error means the `libtermbox.so` could not be found where `ld` is looking for it.

When `ld` is called, it should be provided a `-L the_directory_where_you_.so_is` option. Crystal’s man page says it should be something like that:

```
crystal build src/colorls.cr --link-flags "-L your_directory"
```

If you installed `termbox` in `/usr/local`, the directory in question will be `/usr/local/lib`.

Hope that helps.
